// <auto-generated />
using AspNetCoreAuthCookie.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AspNetCoreAuthCookie.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190125123954_AlterandoDadosInseridosUser3")]
    partial class AlterandoDadosInseridosUser3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AspNetCoreAuthCookie.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("ActiveUser");

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<bool>("RememberMe");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("UserTypes");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new { UserId = 1, ActiveUser = true, Password = "EF797C8118F02DFB64967DD5D3F8C762348C9C63D532CC95C5ED7A898A64F", RememberMe = true, UserName = "Admin", UserTypes = 0 },
                        new { UserId = 2, ActiveUser = true, Password = "EF797C8118F02DFB64967DD5D3F8C762348C9C63D532CC95C5ED7A898A64F", RememberMe = true, UserName = "Manager", UserTypes = 1 },
                        new { UserId = 3, ActiveUser = true, Password = "EF797C8118F02DFB64967DD5D3F8C762348C9C63D532CC95C5ED7A898A64F", RememberMe = true, UserName = "Users", UserTypes = 2 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
